[2024-05-04T17:48:36.158+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.write_to_raw_data_task manual__2024-05-04T17:48:34.920072+00:00 [queued]>
[2024-05-04T17:48:36.162+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.write_to_raw_data_task manual__2024-05-04T17:48:34.920072+00:00 [queued]>
[2024-05-04T17:48:36.162+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-04T17:48:36.167+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): write_to_raw_data_task> on 2024-05-04 17:48:34.920072+00:00
[2024-05-04T17:48:36.173+0000] {standard_task_runner.py:57} INFO - Started process 361 to run task
[2024-05-04T17:48:36.177+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main', 'write_to_raw_data_task', 'manual__2024-05-04T17:48:34.920072+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpiyv5tspf']
[2024-05-04T17:48:36.180+0000] {standard_task_runner.py:85} INFO - Job 121: Subtask write_to_raw_data_task
[2024-05-04T17:48:36.225+0000] {task_command.py:415} INFO - Running <TaskInstance: main.write_to_raw_data_task manual__2024-05-04T17:48:34.920072+00:00 [running]> on host 9fbef72bff90
[2024-05-04T17:48:36.305+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='write_to_raw_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T17:48:34.920072+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T17:48:34.920072+00:00'
[2024-05-04T17:51:58.647+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-05-04T17:51:58.656+0000] {process_utils.py:131} INFO - Sending 15 to group 361. PIDs of all processes in the group: [361]
[2024-05-04T17:51:58.657+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 361
