[2024-05-04T16:55:20.743+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main.write_to_clean_data manual__2024-05-04T16:53:53.417803+00:00 [queued]>
[2024-05-04T16:55:20.748+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main.write_to_clean_data manual__2024-05-04T16:53:53.417803+00:00 [queued]>
[2024-05-04T16:55:20.748+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-04T16:55:20.753+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): write_to_clean_data> on 2024-05-04 16:53:53.417803+00:00
[2024-05-04T16:55:20.759+0000] {standard_task_runner.py:57} INFO - Started process 112 to run task
[2024-05-04T16:55:20.763+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'main', 'write_to_clean_data', 'manual__2024-05-04T16:53:53.417803+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpxsot__aq']
[2024-05-04T16:55:20.766+0000] {standard_task_runner.py:85} INFO - Job 82: Subtask write_to_clean_data
[2024-05-04T16:55:20.803+0000] {task_command.py:415} INFO - Running <TaskInstance: main.write_to_clean_data manual__2024-05-04T16:53:53.417803+00:00 [running]> on host 243a4ba842c9
[2024-05-04T16:55:20.856+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main' AIRFLOW_CTX_TASK_ID='write_to_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T16:53:53.417803+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T16:53:53.417803+00:00'
[2024-05-04T16:55:20.913+0000] {warnings.py:109} WARNING - /opt/***/dags/main.py:60: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2024-05-04T16:55:28.266+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-05-04T16:55:28.289+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=main, task_id=write_to_clean_data, execution_date=20240504T165353, start_date=20240504T165520, end_date=20240504T165528
[2024-05-04T16:55:28.366+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-05-04T16:55:28.387+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
