[2024-04-06T21:28:11.503+0000] {taskinstance.py:1119} INFO - Dependencies not met for <TaskInstance: Data_fetch_dag.fetch_data_task scheduled__2024-04-06T19:10:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-04-06T21:28:11.511+0000] {local_task_job_runner.py:161} INFO - Task is not able to be run
